name: Benchmark

on: [push, pull_request, workflow_dispatch]

permissions: {}

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          allow-prereleases: true

      - name: Install gettext
        run: |
          sudo apt install gettext

      - name: Generate translation binaries
        run: |
          scripts/generate-translation-binaries.sh

      - name: Install dependencies
        run: pip install -e ".[tests]"

      - name: Run benchmarks
        uses: CodSpeedHQ/action@3194d9a39c4d46684cb44bf7207fc56626aad8fd # v4.15.1
        with:
          mode: simulation
          run: pytest tests/test_benchmarks.py --codspeed
