name: Benchmark

on: [push, pull_request, workflow_dispatch]

permissions: {}

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python 3.14
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          allow-prereleases: true

      - name: Install gettext
        run: |
          sudo apt install gettext

      - name: Generate translation binaries
        run: |
          scripts/generate-translation-binaries.sh

      - name: Install dependencies
        run: pip install -e ".[tests]"

      - name: Run benchmarks
        uses: CodSpeedHQ/action@63f3e98b61959fe67f146a3ff022e4136fe9bb9c # v4.17.6
        with:
          mode: simulation
          run: pytest tests/test_benchmarks.py --codspeed
