name: Benchmark

on: [push, pull_request, workflow_dispatch]

permissions: {}

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python 3.14
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
          allow-prereleases: true

      - name: Install gettext
        run: |
          sudo apt install gettext

      - name: Generate translation binaries
        run: |
          scripts/generate-translation-binaries.sh

      - name: Install dependencies
        run: pip install -e ".[tests]"

      - name: Run benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        with:
          mode: simulation
          run: pytest tests/test_benchmarks.py --codspeed
